name: ioc_importer_with_schedule

on:
  schedule:
  - cron: '*/60 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Git configuration
      run: git config --global user.name "Test bot"
    - name: Download IOCs
      #run: curl -L --insecure -o ioc.csv --request GET https://optic.threatstream.com/api/v1/integration/21590/latest/?token=${{ secrets.TOKEN }}
    - name: Display structure of downloaded files
      run: ls -R
    - name: Commit
      run: |
        git fetch
        git pull
        git add ioc.csv
        git diff-index --quiet HEAD || git commit -m "auto update"
        git push
